[package]
name = "disk-array-search"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
bytesize = "1.3"
libc = "0.2"
tokio = { version = "1.49", features = ["full"] }
tokio-util = "0.7"
rayon = "1.10"
memchr = "2.7"